apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio
  namespace: observatorium
spec:
  storageClassName: "{{STORAGECLASS}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "{{OBJ_STORAGE_STORAGE}}"
