apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:thanos-rule
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:thanos-rule
subjects:
- kind: ServiceAccount
  name: observability-thanos-rule
  namespace: open-cluster-management
