apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:alertmanager-accessor
  labels:
    alertmanager: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:alertmanager-accessor
subjects:
- kind: ServiceAccount
  name: observability-alertmanager-accessor
  namespace: open-cluster-management
