apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: apiserver-hcp-user-workload-metrics-collector # Expected label by MCOA for HCPs
    app.kubernetes.io/part-of: multicluster-observability-addon
    app.kubernetes.io/managed-by: multicluster-observability-operator
  name: apiserver-hcp-uwl-rules-default
  namespace: open-cluster-management-observability
spec:
  groups:
  - name: acm-apiserver-hcp-uwl-rules-default
    rules:
    - expr: (histogram_quantile(0.99,sum(rate(apiserver_request_duration_seconds_bucket{component="apiserver",
        verb!="WATCH",clusterID!=""}[5m])) by (le, verb, instance, cluster, clusterID, managementcluster, managementclusterID)))
      record: apiserver_request_duration_seconds:histogram_quantile_99:instance
    - expr: sum(rate(apiserver_request_total{component="apiserver",service="kubernetes",clusterID!=""}[5m])) by (code, instance, cluster, clusterID, managementcluster, managementclusterID)
      record: sum:apiserver_request_total:5m
    - expr: histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job="apiserver",clusterID!=""}[5m])) by (instance, name, le, cluster, clusterID, managementcluster, managementclusterID))
      record: workqueue_queue_duration_seconds_bucket:apiserver:histogram_quantile_99
    - expr: (histogram_quantile(0.99,sum(rate(apiserver_request_duration_seconds_bucket{component="apiserver",
        verb!="WATCH",clusterID!=""}[5m])) by (le, cluster, clusterID, managementcluster, managementclusterID)))
      record: apiserver_request_duration_seconds:histogram_quantile_99
