apiVersion: v1
stringData:
  alertmanager.yaml: |
    "global":
      "resolve_timeout": "5m"
    "receivers":
    - "name": "null"
    "route":
      "group_by":
      - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "null"
      "repeat_interval": "12h"
      "routes":
      - "match":
          "alertname": "Watchdog"
        "receiver": "null"
kind: Secret
metadata:
  name: alertmanager-config
  namespace: open-cluster-management
  annotations:
    skip-creation-if-exist: "true"
type: Opaque