apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:alertmanager
  labels:
    alertmanager: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:alertmanager
subjects:
- kind: ServiceAccount
  name: alertmanager
  namespace: open-cluster-management
