apiVersion: apps/v1
kind: Deployment
metadata:
  name: observatorium-operator
  labels:
    app.kubernetes.io/component: observatorium-operator
    app.kubernetes.io/name: observatorium-operator
    app.kubernetes.io/part-of: observatorium
    control-plane: observatorium-operator
    observability.open-cluster-management.io/name: "{{MULTICLUSTEROBSERVABILITY_CR_NAME}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: observatorium-operator
      observability.open-cluster-management.io/name: "{{MULTICLUSTEROBSERVABILITY_CR_NAME}}"
  template:
    metadata:
      labels:
        control-plane: observatorium-operator
        observability.open-cluster-management.io/name: "{{MULTICLUSTEROBSERVABILITY_CR_NAME}}"
    spec:
      containers:
      - args:
        - --log-level=debug
        image: quay.io/observatorium/observatorium-operator:master-2020-10-09-ecc37fc
        imagePullPolicy: "{{MULTICLUSTEROBSERVABILITY_IMAGE_PULL_POLICY}}"
        name: observatorium-operator
        resources:
          limits:
            cpu: 100m
            memory: 600Mi
          requests:
            cpu: 100m
            memory: 600Mi
      imagePullSecrets:
      - name: "{{MULTICLUSTEROBSERVABILITY_IMAGE_PULL_SECRET}}"
      serviceAccountName: observatorium