resources:
- alerting_rules.yaml
- aggregate_role.yaml
- role.yaml
- role_binding.yaml
- operator.yaml
- service_account.yaml
- observability.open-cluster-management.io_observabilityaddon_crd.yaml
- observability.open-cluster-management.io_observabilityaddon_v1beta1_crd.yaml 