# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- bases/observability.open-cluster-management.io_observabilityaddons.yaml
- bases/core.observatorium.io_observatoria.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_multiclusterobservabilities.yaml
#- patches/webhook_in_observabilityaddons.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [OCP-SSC] To enable webhook with ocp service serving certificate for the CRD, uncomment all the sections with [OCP-SSC] prefix.
# patches here are for enabling webhook with ocp service serving certificate.
- patches/ocp_ssc_webhook_cronjobs.yaml
# +kubebuilder:scaffold:kustomizepatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_multiclusterobservabilities.yaml
#- patches/cainjection_in_observabilityaddons.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
