apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
  namespace: open-cluster-management
type: Opaque
stringData:
  grafana.ini: |
    [auth]
    disable_login_form = true
    disable_signout_menu = true
    [auth.basic]
    enabled = false
    [auth.proxy]
    auto_sign_up = true
    enabled = true
    header_name = X-Forwarded-User
    [paths]
    data = /var/lib/grafana
    logs = /var/lib/grafana/logs
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [security]
    admin_user = WHAT_YOU_ARE_DOING_IS_VOIDING_SUPPORT_0000000000000000000000000000000000000000000000000000000000000000
    cookie_secure = true
    [server]
    http_port = 3001
    #root_url = %(protocol)s://%(domain)s/grafana/
    #domain = localhost
    [users]
    viewers_can_edit = true
    [dataproxy]
    timeout = 300
    dial_timeout = 30
    keep_alive_seconds = 300
    [feature_toggles]
    correlations = false
    [public_dashboards]
    enabled = false
