resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- config.yaml
- deployment.yaml
- service.yaml
- dash-acm-alert-analysis.yaml
- dash-acm-alerts-by-clusters.yaml
- dash-acm-cluster-by-alerts.yaml
- dash-acm-optimization-overview.yaml
- dash-acm-clusters-overview.yaml
- dash-acm-clusters-overview-optimized.yaml
- dash-acm-hcp-overview.yaml
- dash-acm-resources-hcp.yaml
- dash-k8s-etcd.yaml
- dash-k8s-apiserver.yaml
- dash-k8s-networking-cluster.yaml
- dash-k8s-compute-resources-cluster.yaml
- dash-k8s-compute-resources-namespace-pods.yaml
- dash-k8s-compute-resources-namespace-workloads.yaml
- dash-k8s-compute-resources-workload.yaml
- dash-k8s-compute-resources-node-pods.yaml
- dash-k8s-compute-resources-pod.yaml
- dash-k8s-service-level-overview-api-server.yaml
- dash-k8s-service-level-overview-api-server-cluster.yaml
- dash-cluster-rsrc-use.yaml
- dash-node-rsrc-use.yaml
- dash-acm-clusters-overview-ocp311.yaml
- dash-acm-optimization-overview-ocp311.yaml
- dash-k8s-capacity-planning-ocp311.yaml
- dash-k8s-compute-resources-namespace-pods-ocp311.yaml
- dash-k8s-compute-resources-pod-ocp311.yaml
- dash-k8s-namespaces-in-cluster-ocp311.yaml
- dash-k8s-pods-in-namespace-ocp311.yaml
- dash-k8s-summary-by-node-ocp311.yaml
- dash-acm-openshift-virtualization-overview.yaml
- dash-acm-virtual-machines-inventory.yaml
- dash-acm-virtual-machines-by-time-in-status.yaml
- dash-acm-openshift-virtualization-single-cluster-view.yaml
- dash-acm-openshift-virtualization-single-vm-view.yaml
