resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- config.yaml
- deployment.yaml
- service.yaml
- alerts
- analytics
- hcp
- hcp-mcoa
- platform
- platform-mcoa
- virtualization
