apiVersion: monitoring.rhobs/v1alpha1
kind: ScrapeConfig
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: platform-metrics-collector
    app.kubernetes.io/part-of: multicluster-observability-addon
    app.kubernetes.io/managed-by: multicluster-observability-operator
  name: platform-metrics-alerts
  namespace: open-cluster-management-observability
spec:
  jobName: alerts
  metricsPath: /federate
  params:
    match[]:
    - '{__name__="ALERTS",alertname!="PodDisruptionBudgetAtLimit"}'
    - '{__name__="ALERTS",alertname="PodDisruptionBudgetAtLimit",poddisruptionbudget!~"kubevirt-disruption-budget-.*"}'
  metricRelabelings:
  - action: labeldrop
    regex: managed_cluster|id
